### ISSUE TITLE
relationship type should be separate

### ISSUE THREAD

**Issue by zvr** [Yash-Varshney/tools-python#2]
the list of different relationships should not be part of the validation check.

Create a different RelationshipType class, based on Enum, and have them there:
```python
from enum import Enum, auto

class RelationshipType(Enum):
    'DESCRIBES' = auto()
    'DESCRIBED_BY' = auto()
    ...
```

Then the validation can be a simple:
```python
    if my_type in RelationshipType:
        ...
```

**Comment by Yash-Varshney** [comment]
thanks @zvr for informing but the issue this way will be a lengthier code because,
for ex.
```python3
# import enum and auto 
from enum import Enum, auto 
  
# Using enum.auto() method 
class language(Enum): 
    Cpp = auto() 
    JavaScript = auto() 
    Java = auto() 
    Python = auto() 
    HTML = auto() 

a = 'Cpp'

if a not in [
    language.Cpp,
    language.JavaScript,
    language.Java

]:
    print('no')
else:
    print('yes')

```
the above code prints 'no' as 'a' is str, if I use this way I may also need to change the parser & builder.

**Comment by zvr** [comment]
Why are you comparing a string?  In RDF, for example, relationship types are URIs.

Anyway, if you wanted to check string, you can obviously do it:
```python
>>> 'Cpp' in [name for name, _ in language.__members__.items()]
True
```

**Comment by Yash-Varshney** [comment]
Thank you @zvr. I've made the changes regarding this issue in the recent push :)
