### ISSUE TITLE
why are relationships ordered?

### ISSUE THREAD

**Issue by zvr** [Yash-Varshney/tools-python#3]
Why is the Relationship class ordered by using `@total_ordering` ?

When will you ever compare relationships to sort them?

**Comment by Yash-Varshney** [comment]
@zvr there is no particular use of `total_ordering` but it is also used in Annotator class (which is pretty similar in working with relationship) so for maintaining code similarity, I used it here.

**Comment by zvr** [comment]
Unless there is a reason, I'd suggest you remove all this extra code.

**Comment by Yash-Varshney** [comment]
I've removed the `total_ordering` feature from relationship.py file
